### QUESTION-1

 Create a numpy array starting from 2 till 50 with a stepsize of 3.

### Program


In [1]:
import numpy as np

In [6]:
arr= np.arange(start = 2,stop=51,step=3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# QUESTION-2

 Accept two lists of 5 elements each from the user.
 Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [18]:
arr=list(map(int, input().split()))
brr=list(map(int, input().split()))

# converting into numpy array
arr=np.array(arr)
brr=np.array(brr)
print( "")
print( "Lists Converts into numpy arrays")
print(arr)
print(brr)
print( "")

# concatenating these arrays
print("Concatenating the arrays")
z=np.concatenate((arr, brr))
print(z)
print( "")

#Sorting the arrays
print( "Sorting the arrays")
print(np.sort(arr))
print(np.sort(brr))

54 86 24 38
91 50 34 72

Lists Converts into numpy arrays
[54 86 24 38]
[91 50 34 72]

Concatenating the arrays
[54 86 24 38 91 50 34 72]

Sorting the arrays
[24 38 54 86]
[34 50 72 91]


### QUESTION-3

Write a code snippet to find the dimensions of a ndarray and its size.

 #### Code

In [5]:
import numpy as np

arr = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
print(arr.shape,arr.size)

(3, 3) 9


 ### QUESTION-4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

### Code

In [7]:
'''
    To convert a 1D array into a 2D array, we can use reshape(a, newshape, order='C').
    
    e.g arr = np.array([ [1,2,3,4,5,6,7,8,9] ]) 
        
        arr.shape O/P: (1, 9)
        
        arr.reshape(3,3)
        
        O/P: array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
    
'''
arr = np.array([ [1,2,3,4,5,6,7,8,9] ])

print(arr,arr.shape) 

print()

arr = arr.reshape(3,3) 

print(arr,arr.shape)

[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


### QUESTION-5

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

 #### Code

In [8]:

arr1 = np.array([ [1,1,1] , [2,2,2] , [3,3,3] ])
arr2 = np.array([ [4,4,4] , [5,5,5] , [6,6,6] ])
print(np.vstack((arr1,arr2))) # Stack the arrays in a row-wise sequence
print() 
print(np.hstack((arr1,arr2))) # Stack the arrays in a column-wise sequence


[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]

[[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]


#### QUESTION-6

How to get unique items and counts of unique items?

#### Code

In [9]:
list1 = [1,3,1,5,2,4]
list1 = list(set(list1))
print(list1)
print()
print(len(list1))

[1, 2, 3, 4, 5]

5
